### ISSUE TITLE
Add get() to easily access DOM

### ISSUE THREAD

**Issue by creativefctr** [UrielCh/puppeteer-jquery#1]
Hi,
The get method would make it very convenient to access DOM directly and do some low level stuff.
+ a question: In order to add a new method, shall we do anything more than adding the signature to PJQuery.ts?
Thanks for the great implementation

**Comment by UrielCh** [comment]
hi,

`Add get() to easily access DOM` i'm not sure of that you want.

for the second question, feel free to propose any better alternative. for not I did not find any cleaner solution.
