### ISSUE TITLE
ReferenceError: ${jQueryName} is not defined when execute waitForjQuery with playwright 1.21.1

### ISSUE THREAD

**Issue by Luxusio** [UrielCh/puppeteer-jquery#11]
I'm using
> playwright 1.21.1
> playwright-jquery: 0.3.1
> OS : macOS Monterey 12.3.1
> CPU : Apple M1
> Node : 16.13.1

I got following error message when use `waitForjQuery()`
> page.evaluateHandle: ReferenceError: i_1hp2uo3je2j is not defined

Stack Trace
> at eval (eval at evaluate (:152:29), <anonymous>:1:1)
> at eval (<anonymous>)
> at UtilityScript.evaluate (<anonymous>:152:29)
> at UtilityScript.<anonymous> (<anonymous>:1:44)
> at PProxyApi.exec (--/node_modules/playwright-jquery/lib/jQueryPlugin.js:137:37)
> at Proxy.<anonymous> (--/node_modules/playwright-jquery/lib/jQueryPlugin.js:65:35)
> at Page.waitForjQuery (--/node_modules/playwright-jquery/lib/jQueryPlugin.js:26:51)

**Comment by UrielCh** [comment]
Fixed in 0.3.3
