### ISSUE TITLE
.attr( 'href' ) doesn't' give the expected value.

### ISSUE THREAD

**Issue by KLA6** [UrielCh/puppeteer-jquery#3]
E.g. in the below case,
```
await page.jQuery( 'div' ).eq( 0 ).find( 'a' ).eq( 0 ).attr( 'href' )
```
It shows an error as the below.
```
failed:Evaluation failed: TypeError: n_2gzirqb0dcw(...).eq(...).find(...).eq(...).attr(...).toArray is not a function
```
BTW, this works normally.
```
await page.jQuery( 'div' ).eq( 0 ).find( 'a' ).eq( 0 ).text()
```
in this library, attr() is not possible to use...?

**Comment by UrielCh** [comment]
Hi, I had given up pptr, for some time, due to poor typescript support, with puppeter 8.0.0, that fixed.

now with pptr 8.0.0, I'm back in track.

.attr, .css, .prop is now fully support.
