### ISSUE TITLE
How to get selected dom length

### ISSUE THREAD

**Issue by hoperyy** [UrielCh/puppeteer-jquery#8]
```js
page.jQuery('#form').length
```

It won't return a number. How to get the wright value ?

Thanks!

**Comment by UrielCh** [comment]
page.jQuery('#form') is a promise, it should be awaited first.

**Comment by bendehghan** [comment]
the interface says page.jQuery is not async. 
How do you get the length now?

**Comment by UrielCh** [comment]
I'm not sure, try:
```ts
const forms = await page.jQuery('#form').exec();
console.log(forms.length);
```

```ts
page.jQuery('#form')
```
 is not a real promise, but contains a then function compatible with regular Promise
