### ISSUE TITLE
Remove console.error.

### ISSUE THREAD

**Issue by hotrungnhan** [UrielCh/puppeteer-jquery#9]
https://github.com/UrielCh/puppeteer-jquery/blob/1b484d2b3b2c979eebeb43d822ffeeb2b3fd976a/puppeteer-jquery/src/jQueryPlugin.ts#L175
Althoght i catch the error this line still show up , anoying me. Plz remove this on the next version , or you can add a option to disable this . TKSS

**Comment by UrielCh** [comment]
puppeteer-jquery@0.3.2 is out without console.error

**Comment by hotrungnhan** [comment]
> puppeteer-jquery@0.3.2 is out without console.error
Great , tks for your help.
